apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80         # service port
      targetPort: 80   # container port
      nodePort: 30081  # external port (optional; can omit to let k8s auto-assign within 30000-32767)
